// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEPueN1GkeAWB1BTWStCMJcX9wai_pqU',
    appId: '1:231977102251:web:14dd833f4d426adb3900ee',
    messagingSenderId: '231977102251',
    projectId: 'colegioespecialdgp',
    authDomain: 'colegioespecialdgp.firebaseapp.com',
    databaseURL: 'https://colegioespecialdgp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'colegioespecialdgp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPJlgGrtEgnTJ3sl4b7Pv_u6bIMMpn0-g',
    appId: '1:231977102251:android:32c35a48e89caaae3900ee',
    messagingSenderId: '231977102251',
    projectId: 'colegioespecialdgp',
    databaseURL: 'https://colegioespecialdgp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'colegioespecialdgp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1BUCGtWfDlX29JWW7as0SXTi3cHXAis',
    appId: '1:231977102251:ios:5548e1ccf9d7617e3900ee',
    messagingSenderId: '231977102251',
    projectId: 'colegioespecialdgp',
    databaseURL: 'https://colegioespecialdgp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'colegioespecialdgp.appspot.com',
    iosClientId: '231977102251-v6hcg0uf9vbb1265b02v0ftu3r39l47d.apps.googleusercontent.com',
    iosBundleId: 'com.example.colegioEspecialDgp',
  );
}
