// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd0ZQxAA1sdx1L2qzwIaRwjArbc1792Go',
    appId: '1:85240334260:web:9a2ad40f269a5ffe0954e1',
    messagingSenderId: '85240334260',
    databaseURL: 'https://proyectoprueba-56640-default-rtdb.firebaseio.com/',
    projectId: 'proyectoprueba-56640',
    authDomain: 'proyectoprueba-56640.firebaseapp.com',
    storageBucket: 'proyectoprueba-56640.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoc8y0kLqq50XAVomKSpXowqqh0HTwcwU',
    appId: '1:85240334260:android:522cf2809d3f2eb40954e1',
    messagingSenderId: '85240334260',
    projectId: 'proyectoprueba-56640',
    storageBucket: 'proyectoprueba-56640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZkAK2FcP02phmnd3xvM_Uwxz_KFssDtY',
    appId: '1:85240334260:ios:f4e342e725e7a4530954e1',
    messagingSenderId: '85240334260',
    projectId: 'proyectoprueba-56640',
    storageBucket: 'proyectoprueba-56640.appspot.com',
    iosClientId: '85240334260-9jn6l1fe44lopmovs800djudgt09f1vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.colegioEspecialDgp',
  );
}
